Fix: Error when use live-dl download a video on youtube
CUID# - Download aborted.
Exception: [AbstractCommand.cc:351] errorCode=24   -> [HttpSkipResponseCommand.cc:215] errorCode=24 Authorization failed.

Reason: aria2 option causes error when using with youtube
Refer: https://github.com/jim60105/live-dl/commit/f30ea474b4fb5b7daf07b0f3776c23bfc9a07592